import { useEffect,useRef,useState } from "react";
import maplibregl,{Map} from "maplibre-gl";
import "maplibre-gl/dist/maplibre-gl.css";
import type { CityPlan,MapCenter } from "../types/city";
import { facilitiesGeoJson,roadsGeoJson,zonesGeoJson } from "../utils/geojson";
type Mode="CURRENT"|"PLAN"|"COMPARE";
export default function CityMap({center,plan}:{center:MapCenter;plan:CityPlan|null}){
 const host=useRef<HTMLDivElement>(null),mapRef=useRef<Map|null>(null);
 const [mode,setMode]=useState<Mode>("PLAN"),[is3d,set3d]=useState(false),[error,setError]=useState("");
 useEffect(()=>{if(!host.current)return;const map=new maplibregl.Map({container:host.current,style:import.meta.env.VITE_MAP_STYLE_URL||"https://demotiles.maplibre.org/style.json",center:[center.longitude,center.latitude],zoom:12});mapRef.current=map;map.addControl(new maplibregl.NavigationControl(),"top-right");map.on("error",e=>{if((e.error?.message||"").includes("style"))setError("지도 스타일을 불러오지 못했습니다. 스타일 URL을 확인해주세요.")});return()=>map.remove()},[center.latitude,center.longitude]);
 useEffect(()=>{const map=mapRef.current;if(!map)return;const render=()=>{for(const id of ["facilities","roads","zones"]){if(map.getLayer(id))map.removeLayer(id);if(map.getSource(id))map.removeSource(id)}if(!plan||mode==="CURRENT")return;map.addSource("zones",{type:"geojson",data:zonesGeoJson(plan.zones)});if(is3d)map.addLayer({id:"zones",type:"fill-extrusion",source:"zones",paint:{"fill-extrusion-color":"#2a9d8f","fill-extrusion-height":40,"fill-extrusion-opacity":mode==="COMPARE"?.35:.65}});else map.addLayer({id:"zones",type:"fill",source:"zones",paint:{"fill-color":"#2a9d8f","fill-opacity":mode==="COMPARE"?.2:.42}});map.addSource("roads",{type:"geojson",data:roadsGeoJson(plan.roads)});map.addLayer({id:"roads",type:"line",source:"roads",paint:{"line-color":["match",["get","roadType"],"BRT","#ef8354","BICYCLE","#2a9d8f","SUBWAY","#7b2cbf","#f4a261"],"line-width":["match",["get","roadType"],"BRT",6,"BUS",2,4],"line-opacity":mode==="COMPARE"?.45:.85,"line-dasharray":[2,1]}});map.addSource("facilities",{type:"geojson",data:facilitiesGeoJson(plan.facilities)});map.addLayer({id:"facilities",type:"circle",source:"facilities",paint:{"circle-radius":8,"circle-color":["match",["get","facilityType"],"PARK","#2a9d8f","HOSPITAL","#e63946","SCHOOL","#4361ee","#f4a261"],"circle-stroke-color":"#fff","circle-stroke-width":2,"circle-opacity":mode==="COMPARE"?.55:1}});for(const id of ["facilities","roads","zones"])map.on("click",id,e=>{const f=e.features?.[0];if(f)new maplibregl.Popup().setLngLat(e.lngLat).setHTML(`<strong>${String(f.properties?.name||"계획 객체")}</strong><p>${String(f.properties?.reason||"")}</p>`).addTo(map)})};map.isStyleLoaded()?render():map.once("load",render)},[plan,mode,is3d]);
 useEffect(()=>{mapRef.current?.easeTo({pitch:is3d?55:0,bearing:is3d?-12:0,duration:500})},[is3d]);
 return <section className="card map-card"><div className="map-toolbar"><div>{(["CURRENT","PLAN","COMPARE"] as Mode[]).map((x,i)=><button className={mode===x?"active":"secondary"} key={x} onClick={()=>setMode(x)}>{["현재 상태","AI 계획안","전체 비교"][i]}</button>)}</div><button className="secondary" onClick={()=>set3d(v=>!v)}>{is3d?"2D로 보기":"3D로 보기"}</button></div>{error&&<p className="inline-warning">{error}</p>}<div ref={host} className="map"/><div className="legend"><span>● 시설</span><span>━ 도로·노선</span><span>■ 개발 구역</span></div></section>
}
