import { useEffect,useState } from "react";
import { Link,useParams } from "react-router-dom";
import { getCityAnalysis } from "../api/cityApi";
import AgentAnalysisPanel from "../components/AgentAnalysisPanel";
import CityMap from "../components/CityMap";
import PlanCards from "../components/PlanCards";
import PlanComparison from "../components/PlanComparison";
import ScoreOverview from "../components/ScoreOverview";
import WarningPanel from "../components/WarningPanel";
import type { CityAnalysisRequest,CityAnalysisResponse,CityPlan } from "../types/city";
import { date,money,population } from "../utils/format";
export default function AnalysisPage(){const {analysisId=""}=useParams(),[data,setData]=useState<CityAnalysisResponse>(),[selected,setSelected]=useState<CityPlan|null>(null),[error,setError]=useState("");const load=()=>{setError("");getCityAnalysis(analysisId).then(x=>{setData(x);setSelected(x.plans[0]||null)}).catch(e=>setError((e instanceof Error&&e.message.includes("404"))?"분석 결과를 찾을 수 없습니다.":e instanceof Error?e.message:"분석 조회에 실패했습니다."))};useEffect(load,[analysisId]);if(error)return <main className="state card"><h1>분석 결과를 불러오지 못했습니다</h1><p>{error}</p><div className="actions"><button onClick={load}>다시 시도</button><Link className="button secondary" to="/">홈으로 돌아가기</Link></div></main>;if(!data)return <main className="state"><p>분석 결과를 불러오는 중입니다.</p></main>;let request:CityAnalysisRequest|undefined;try{request=JSON.parse(sessionStorage.getItem(`analysis-request:${analysisId}`)||"") as CityAnalysisRequest}catch{request=undefined}const center=request?.mapCenter||{latitude:35.16,longitude:129.16};return <main><section className="overview"><div><p className="eyebrow">분석 결과</p><h1>{data.cityName} {data.districtName}</h1><p>생성 시각 {date(data.createdAt)}</p></div>{request?<dl><div><dt>인구</dt><dd>{population(request.population)}</dd></div><div><dt>면적</dt><dd>{request.areaKm2}km²</dd></div><div><dt>총예산</dt><dd>{money(request.totalBudget)}</dd></div><div><dt>우선 목표</dt><dd>{request.priorityGoals.join(", ")||"없음"}</dd></div></dl>:<p className="notice">새로고침 복원 응답에는 입력 도시 개요가 포함되지 않습니다.</p>}</section><ScoreOverview scores={data.currentScores}/><div className="dashboard"><CityMap center={center} plan={selected}/><AgentAnalysisPanel items={data.agentAnalyses||[]}/></div><PlanCards plans={data.plans||[]} selected={selected?.planType||null} onSelect={setSelected}/><PlanComparison plans={data.plans||[]}/><WarningPanel warnings={data.warnings||[]}/></main>}
